initial React version of the website and docs
aml-org/a-ml pull request #14
Opened 2020-12-28 14:20 UTC by arielmirra

This PR matches the current stg.a.ml website and adds the AML/AMF documentation. Everything is implemented in React framework using Docusaurus library.

2020-12-29 00:12 UTC, jstoiko requested changes
A few things (aside from my other comments):
- [ ] docker/docker compose does not seem to work
- [ ] site cannot (npm/yarn) start from `/` (setting `baseUrl` in `website/docusaurus.config.js` to `/` instead of `/amf-documentation/` break all images)
- [ ] when (npm run) build-ing the site and then (npm run) serve-ing it as is, it won't work unless changing the `baseUrl` in `website/docusaurus.config.js` to `/`

2020-12-29 15:42 UTC, arielmirra commented on website/docusaurus.config.js
> +    baseUrl: '/amf-documentation/',
can't seem to reproduce the issue with images, I've updated the baseUrl to `'/'` and everything works as intented.

2020-12-29 17:00 UTC, arielmirra commented
> A few things (aside from my other comments):
> 
> * [ ]  docker/docker compose does not seem to work
> * [ ]  site cannot (npm/yarn) start from `/` (setting `baseUrl` in `website/docusaurus.config.js` to `/` instead of `/amf-documentation/` break all images)
> * [ ]  when (npm run) build-ing the site and then (npm run) serve-ing it as is, it won't work unless changing the `baseUrl` in `website/docusaurus.config.js` to `/`
> * [x]  seems like there is a default `/blog/` subfolder being built but it's empty, I would remove it
> * [ ]  feels a little odd to have the root-level website source code inside a `/website` folder, I would try to move it to the root of the repo

The configuration file has been updated in the latest commit, everything should work just fine.
I've removed the unused blog folder
Regarding the folder structure, it can't be changed due to the framework being used (docusaurus), but I've added a root-level `package.json` file with two valuable scripts to simplify building:
- `npm run preview` serves the live view of the website
- `npm run build` build the static site and serves it
both run the server in localhost:3000.

I've updated the `README.md` to reflect this changes.

2021-01-20 17:32 UTC, jstoiko approved these changes

2021-01-20 17:32 UTC, merged