APIMF-2775: add custom resource loader documentation
aml-org/a-ml pull request #22
Opened 2021-03-02 15:43 UTC by arielmirra

APIMF-2775: add custom resource loader documentation

2021-03-02 20:34 UTC, IsaacEldridge requested changes

2021-03-02 20:34 UTC, IsaacEldridge commented on docs/custom/resource-loaders.mdx
> +    - the URI is transformed to `external%20file.json` by removing the relative path and folder structure
The relative path and folder structure are removed, the URI is transformed to `external%20file.json`.

2021-03-02 20:34 UTC, IsaacEldridge commented on docs/custom/resource-loaders.mdx
> +    - as the reference was relative, this step appends the URI of the main file to the base of the reference URI: `file:///Users/user/external%20file.json`
- The reference was relative, so the URI of the of the main file is appended to the base of the reference URI: `file:///Users/user/external%20file.json`.

2021-03-02 20:34 UTC, IsaacEldridge commented on docs/custom/resource-loaders.mdx
> +Finally, resource loaders will receive the following the normalized URI to fetch the json file: `file:///Users/user/external%20file.json`.
Finally, resource loaders will use the following normalized URI to fetch the JSON file: `file:///Users/user/external%20file.json`.

2021-03-02 20:34 UTC, IsaacEldridge commented on docs/custom/resource-loaders.mdx
> +## Code example
## Example code for a custom resource loader

2021-03-02 20:34 UTC, IsaacEldridge commented on docs/custom/resource-loaders.mdx
> +The following code is an example of a custom Resource Loader that is able to obtain resources using a custom protocol:
The following example code is for a custom resource loader that obtains resources using a custom protocol:

2021-03-03 16:24 UTC, arielmirra commented on docs/custom/resource-loaders.mdx
> +  - FileResourceLoader
was hesitating to do it, but they're literally things inside the AMF code, so yes

2021-03-03 16:31 UTC, arielmirra commented on docs/custom/resource-loaders.mdx
> +The fetch method encapsulates the actual loading of the resource, which depends on your implementation, but always returns a future (or promise) of a Content object.
That's almost correct! Promise/Observable/Future/etc. are all implementations in different languages of asynchronous calls. I've reformatted the text to generalize that. thanks!

2021-03-04 16:45 UTC, arielmirra commented on docs/custom/resource-loaders.mdx
> +Within this Environment you can directly add your custom resource loaders, or even delete the ones provided by AMF:
True, but the process of deleting the ones provided by AMF is not a straightforward one, I'll delete that part and add it if a refactor is made.

2021-03-04 17:11 UTC, arielmirra commented on docs/custom/resource-loaders.mdx
> +Before fetching, every URI goes through processing called **normalization** to ensure consistency and standardization.
Much better, thanks

2021-03-04 19:29 UTC, looseale submitted a review, later dismissed

2021-03-08 16:37 UTC, IsaacEldridge approved these changes

2021-03-08 16:38 UTC, merged